name: Image Generate

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '* * * * *'

jobs:
  generate_calendar_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm install

      - name: Generate
        run: |
          node black.js
      
      - name: Commit
        run: |
          set -x
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git add images
          git commit -m 'generate'
          git push -f
